apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platformui-Chart.fullname" . }}
  labels:
    {{- include "platformui-Chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}

spec:
  ingressClassName: {{ .Values.ingress.ingresClassName }}
  rules:
  - http:
      paths:
        {{- toYaml .Values.ingress.paths | nindent 8 }}
